### ISSUE TITLE
Missing User Parameter

### ISSUE THREAD

**Issue by ibigfire** [misobarisic/redgifs-downloader-desktop#1]
Hello!  This looks really useful, but it's missing the "User" parameter for downloading the clips from a specific user.

I'm trying to download all the clips from a specific user, so it's essential for that purpose.

**Comment by misobarisic** [comment]
@ibigfire I'm afraid that's impossible due to their Redgifs 2021 API upgrade. 

Main project is located [here](https://github.com/misobarisic/redgifs-downloader). You used to be able to download all gifs from a user and search for specific queries and sort by popularity (or whatever) and apply filters for downloading. They first removed the ability to publicly see all user's gifs and now query searching no longer works as well. 

It is not up to me unfortunately.

**Comment by ibigfire** [comment]
Aw nuts, that sucks.  There's a few users I was hoping to grab all the clips uploaded by them that were publicly available, just in case something happened and they disappeared as sometimes happens.  But I really appreciate the response and explanation, thank you very much!  💙

**Comment by misobarisic** [comment]
Downloading specific user's gifs is available in version v0.1.1. Make sure to utilize it until redgifs start removing everything.

**Comment by ibigfire** [comment]
That worked perfectly, thanks so much!  You rock!
